version: "3"
services:
  web:
    restart: always
    build: .
    volumes:
      # Mounts the project directory on the host to /app inside the container,
      # allowing you to modify the code without having to rebuild the image.
      - .:/usr/src/app
      # Just specify a path and let the Engine create a volume.
      # Data present in the base image at the specified mount point will be copied
      # over to the new volume upon volume initialization.
      # node_modules from this new volume will be used and not from your local dev env.
      - /usr/src/app/node_modules/
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      -  MONGOURL=mongodb://mongodb/node-boilerplate
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"